# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4951cc7a5f2dabde1134909a6fa401a2b1fa3713a66413d6dbfa8f125e5aed8e28318d178e7c99f96958dd11316a1f8070ff0a7171db69145de0bb096740fe5

test:
  secret_key_base: dcdb746fb9ad785d636ecc908bd7887140752eb65654dbce7ed82a974863850e20b047d4365473f9a2c221fa50faa5ed6282d72cd5727f971ff1de7c7883fda0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
